spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tg_robot?characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: a123bc
    driver-class-name: com.mysql.cj.jdbc.Driver
